---    

# - name: apt update
#   shell: apt update

- name: Delete repo if it exists
  file:
    path: /var/lib/jenkins/workspace/firstBuild/BirthDateAppFlask/
    state: absent
- name: clone repo
  shell: git clone https://github.com/nathanforester/BirthDateAppFlask.git

# - name: Create a directory if it does not exist
#   ansible.builtin.file:
#     path: /home/ubuntu/myDir
#     state: directory
#     mode: '0755'
#     owner: ubuntu
#     group: ubuntu


- name: Install python venv
  ansible.builtin.apt:
    name: python3.12-venv

# - name: Install Python 3.10.12 venv
#   ansible.builtin.apt:
#     name: python3.10.12-venv
#     state: present
#     update_cache: yes


# - name: add safe repo using shell
#   shell: config --global --add safe.directory /home/ubuntu/myDir

# - name: Clone a repo with separate git directory
#   ansible.builtin.git:
#     repo: https://github.com/nathanforester/BirthDateAppFlask.git
#     dest: /home/ubuntu/myDir/
